### ISSUE TITLE
Nathan Visualization Exercise Review- Sara Benist

### ISSUE THREAD

**Issue by SarBen811** [Nwgreen6283/nathangreenslit-MADA-portfolio#3]
Great job on recreating the graphs! They look really close to the original.

Notes:
Your website is laid out really well, and I like the header separation for the difference steps. The comments in your code also helped with following why you are doing a step. 

The way your code is laid out works well for reproducibility, but for the website, I think it could be helpful to show a couple of rows on the new datasets you create. Just so the audience can visually see the changes you made.

For the case_when() step that specifies the countries of interest, you mentioned that the put all other countries in the "other" category, but I don't see that step in the code.

For the new time columns (time2), why did you have to specify the time as numeric? What was it originally?

The plotting code is nice to follow with it broken into chunks. Super cool that you found the fivethirtyeight theme! I'm excited to see how my graph changes. 

Your caption idea to get '18 in the correct place works, I think if you wanted to go the long way, you could use scale_x_continuous(breaks = c(1900, 1920, 1930... 2018) which should give you the breaks you need. It might also figure out your issue with lining up the '18 line!

Similar idea with y axis to fix the 02:00:00 to 2:00:00 - theme(axis.text.y = element_text(c("2:00:00"...))

I think you also might be slightly off when color-coding the countries; I used a color finder or hue finder online and a screen shot of my graph to find the right hex codes. 

Overall, awesome job and it was pretty easy to follow along with your code!

**Comment by Nwgreen6283** [comment]
**REPLIES**

1. The way your code is laid out works well for reproducibility, but for the website, I think it could be helpful to show a couple of rows on the new datasets you create. Just so the audience can visually see the changes you made.
- Agreed! 

2. For the case_when() step that specifies the countries of interest, you mentioned that the put all other countries in the "other" category, but I don't see that step in the code.
- Technically, anything that was not any of the three countries was categorized as NA. I rephrased this sentence for clarity. 

3. For the new time columns (time2), why did you have to specify the time as numeric? What was it originally?
- Because the data came as time intervals hh:mm:ss, R classified it as "unknown", so I restructured it as numeric to come out as seconds. I added a comment for this. 


4. Your caption idea to get '18 in the correct place works, I think if you wanted to go the long way, you could use scale_x_continuous(breaks = c(1900, 1920, 1930... 2018) which should give you the breaks you need. It might also figure out your issue with lining up the '18 line!
- Oh sweet! I was able to label the whole x axis, correctly but still am not able to get the 2018 years to line up. 

5. Similar idea with y axis to fix the 02:00:00 to 2:00:00 - theme(axis.text.y = element_text(c("2:00:00"...))
- Unfortunately, this still gave me an error: `Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found`

6. I think you also might be slightly off when color-coding the countries; I used a color finder or hue finder online and a screen shot of my graph to find the right hex codes.
- Did not know about this! I did a test run and couldn't get it to match up still. Some of the colors were too neon or bright. I will keep at it. 
Thank you!!
